# Generated by Django 5.1.7 on 2025-03-28 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strand',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
