# Generated by Django 5.1.7 on 2025-07-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_teacherdocument_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdocument',
            name='extension',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
