# Generated by Django 5.1.7 on 2025-07-12 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_teacherdocument_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubStrandReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(max_length=100)),
                ('sub_strand', models.CharField(max_length=100)),
                ('reference_text', models.TextField(help_text='Paste in sample questions, model answers, key facts, etc., aligned to this CBC sub-strand.')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_references', to='rag.teacherdocument')),
            ],
            options={
                'unique_together': {('strand', 'sub_strand')},
            },
        ),
    ]
