# Generated by Django 5.1.7 on 2025-07-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_substrandreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substrandreference',
            name='approved',
        ),
    ]
