# Generated by Django 5.1.7 on 2025-07-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_remove_substrandreference_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substrandreference',
            name='sub_strand',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
