# Generated by Django 5.1.7 on 2025-07-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0006_alter_substrandreference_sub_strand'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdocument',
            name='generation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherdocument',
            name='is_chunking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherdocument',
            name='status',
            field=models.CharField(choices=[('Unapproved', 'Unapproved'), ('Chunking', 'Chunking'), ('Success', 'Success'), ('Failed', 'Failed')], default='Unapproved', max_length=25),
        ),
    ]
