# Generated by Django 5.1.7 on 2025-07-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0007_teacherdocument_generation_error_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='substrandreference',
            unique_together=set(),
        ),
    ]
