# Generated by Django 5.1.7 on 2025-05-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termscore',
            name='expectation_level',
            field=models.CharField(blank=True, choices=[('Below', 'Below'), ('Approaching', 'Approaching'), ('Meeting', 'Meeting'), ('Exceeding', 'Exceeding')], max_length=100),
        ),
    ]
