# Generated by Django 5.1.7 on 2025-03-28 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='termscore',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'grade', 'teacher')},
        ),
    ]
