# Generated by Django 5.1.7 on 2025-03-28 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_alter_class_grade_alter_termscore_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='termscore',
            name='term',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'classroom')},
        ),
    ]
