# Generated by Django 5.1.7 on 2025-05-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='class_obj',
            new_name='classroom',
        ),
    ]
