# Generated by Django 5.1.7 on 2025-05-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamsession',
            name='start_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
