# Generated by Django 5.1.7 on 2025-05-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_studentexamsessionanswer_ai_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamsessionanswer',
            name='expectation_level',
            field=models.CharField(blank=True, choices=[('Below', 'Below'), ('Approaching', 'Approaching'), ('Meeting', 'Meeting'), ('Exceeding', 'Exceeding')], max_length=100, null=True),
        ),
    ]
