# Generated by Django 5.1.7 on 2025-05-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_class_obj_exam_classroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestion',
            old_name='skill_id',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='skill_name',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='strand_id',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='strand_name',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='sub_strand_id',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='sub_strand_name',
        ),
        migrations.RemoveField(
            model_name='examquestionanalysis',
            name='difficulty_distribution',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='answer_options',
            field=models.CharField(default='', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examquestion',
            name='bloom_skill',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question_options',
            field=models.CharField(default='', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examquestion',
            name='strand',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examquestion',
            name='sub_strand',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examquestionanalysis',
            name='strand_distribution',
            field=models.CharField(default='', max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classexamperformance',
            name='bloom_skill_scores',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='examquestionanalysis',
            name='bloom_skill_distribution',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='examquestionanalysis',
            name='grade_distribution',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='examquestionanalysis',
            name='sub_strand_distribution',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='studentexamsessionperformance',
            name='bloom_skill_scores',
            field=models.CharField(max_length=1500),
        ),
    ]
