# Generated by Django 5.1.7 on 2025-05-05 07:05

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_rename_skill_id_examquestion_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='generation_config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='generation_error',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='bloom_skill_options',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='classexamperformance',
            name='bloom_skill_scores',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='classexamperformance',
            name='strand_scores',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.CharField(default=utils.generate_unique_code, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_min',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('Generating', 'Generating'), ('Failed', 'Failed'), ('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Grading', 'Grading'), ('Complete', 'Complete'), ('Archive', 'Archive')], default='Generating', max_length=25),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='answer_options',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_options',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examquestionanalysis',
            name='bloom_skill_distribution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examquestionanalysis',
            name='grade_distribution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examquestionanalysis',
            name='strand_distribution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examquestionanalysis',
            name='sub_strand_distribution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentexamsessionperformance',
            name='bloom_skill_scores',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentexamsessionperformance',
            name='strand_scores',
            field=models.TextField(blank=True),
        ),
    ]
