# Generated by Django 5.1.7 on 2025-05-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_studentexamsessionanswer_expectation_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_analysing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentexamsessionperformance',
            name='completion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentexamsessionperformance',
            name='grade_scores',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentexamsessionperformance',
            name='questions_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexamsessionperformance',
            name='questions_unanswered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexamsessionperformance',
            name='sub_strand_scores',
            field=models.TextField(blank=True),
        ),
    ]
