# Generated by Django 5.1.7 on 2025-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_is_analysing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamsession',
            name='avg_score',
        ),
        migrations.RemoveField(
            model_name='studentexamsession',
            name='expectation_level',
        ),
        migrations.AddField(
            model_name='studentexamsessionperformance',
            name='best_5_question_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentexamsessionperformance',
            name='worst_5_question_ids',
            field=models.TextField(blank=True),
        ),
    ]
