# Generated by Django 5.1.7 on 2025-05-27 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_studentexamsession_avg_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classexamperformance',
            name='classroom',
        ),
        migrations.AddField(
            model_name='classexamperformance',
            name='expectation_level_distribution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classexamperformance',
            name='grade_scores',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classexamperformance',
            name='strong_bloom_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classexamperformance',
            name='strong_sub_strands',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classexamperformance',
            name='sub_strand_scores',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classexamperformance',
            name='weak_bloom_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classexamperformance',
            name='weak_sub_strands',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='classexamperformance',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_exam_performance', to='exam.exam'),
        ),
    ]
