# Generated by Django 5.1.7 on 2025-05-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_classexamperformance_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classexamperformance',
            name='score_distribution',
            field=models.TextField(blank=True),
        ),
    ]
