# Generated by Django 5.1.7 on 2025-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_classexamperformance_score_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamsessionperformance',
            name='class_avg_difference',
            field=models.FloatField(default=0.0),
        ),
    ]
