# Generated by Django 5.1.7 on 2025-05-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_studentexamsessionperformance_class_avg_difference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField()),
                ('score_distribution', models.TextField(blank=True)),
                ('answers_by_level', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='exam.examquestion')),
            ],
        ),
    ]
