# Generated by Django 5.1.7 on 2025-05-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_examquestionperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestionperformance',
            name='avg_expectation_level',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
