# Generated by Django 5.1.7 on 2025-05-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_examquestionperformance_avg_expectation_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestionanalysis',
            name='untested_strands',
            field=models.TextField(blank=True),
        ),
    ]
