# Generated by Django 5.1.7 on 2025-05-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_examquestionanalysis_untested_strands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classexamperformance',
            old_name='strand_scores',
            new_name='bloom_skill_mastery',
        ),
        migrations.RenameField(
            model_name='classexamperformance',
            old_name='strong_bloom_skills',
            new_name='strand_analysis',
        ),
        migrations.RenameField(
            model_name='classexamperformance',
            old_name='strong_sub_strands',
            new_name='strand_student_mastery',
        ),
        migrations.RenameField(
            model_name='classexamperformance',
            old_name='sub_strand_scores',
            new_name='sub_strand_correlation',
        ),
        migrations.RemoveField(
            model_name='classexamperformance',
            name='weak_bloom_skills',
        ),
        migrations.RemoveField(
            model_name='classexamperformance',
            name='weak_sub_strands',
        ),
        migrations.RemoveField(
            model_name='studentexamsessionperformance',
            name='sub_strand_scores',
        ),
    ]
