# Generated by Django 5.1.7 on 2025-06-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_rename_strand_scores_classexamperformance_bloom_skill_mastery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classexamperformance',
            old_name='bloom_skill_mastery',
            new_name='flagged_sub_strands',
        ),
        migrations.RenameField(
            model_name='classexamperformance',
            old_name='sub_strand_correlation',
            new_name='score_variance',
        ),
        migrations.AddField(
            model_name='classexamperformance',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
    ]
