# Generated by Django 5.1.7 on 2025-06-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_rename_bloom_skill_mastery_classexamperformance_flagged_sub_strands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classexamperformance',
            name='general_insights',
            field=models.TextField(blank=True),
        ),
    ]
