# Generated by Django 5.1.7 on 2025-06-03 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_classexamperformance_general_insights'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPerformanceCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_label', models.CharField(max_length=10)),
                ('cluster_size', models.IntegerField(default=0)),
                ('student_session_ids', models.TextField()),
                ('avg_score', models.FloatField()),
                ('avg_expectation_level', models.CharField(blank=True, max_length=100)),
                ('score_variance', models.TextField(blank=True)),
                ('bloom_skill_scores', models.TextField(blank=True)),
                ('strand_scores', models.TextField(blank=True)),
                ('top_best_question_ids', models.TextField(blank=True)),
                ('top_worst_question_ids', models.TextField(blank=True)),
                ('insight', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_clusters', to='exam.exam')),
            ],
        ),
    ]
