# Generated by Django 5.1.7 on 2025-06-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_examperformancecluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='performance_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_exams', to='exam.examperformancecluster'),
        ),
        migrations.AddField(
            model_name='exam',
            name='source_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('FollowUp', 'FollowUp')], default='Standard', max_length=25),
        ),
    ]
