# Generated by Django 5.1.7 on 2025-06-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_exam_performance_cluster_exam_source_exam_exam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examperformancecluster',
            name='insight',
        ),
        migrations.AddField(
            model_name='examperformancecluster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
