# Generated by Django 5.1.7 on 2025-06-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_remove_examperformancecluster_insight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examperformancecluster',
            name='student_session_ids',
        ),
        migrations.AddField(
            model_name='studentexamsessionperformance',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='exam.examperformancecluster'),
        ),
    ]
