# Generated by Django 5.1.7 on 2025-06-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_remove_examperformancecluster_student_session_ids_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentexamsessionperformance',
            old_name='best_5_question_ids',
            new_name='best_5_answer_ids',
        ),
        migrations.RenameField(
            model_name='studentexamsessionperformance',
            old_name='worst_5_question_ids',
            new_name='worst_5_answer_ids',
        ),
    ]
