# Generated by Django 5.1.7 on 2025-06-17 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_rename_best_5_question_ids_studentexamsessionperformance_best_5_answer_ids_and_more'),
        ('learner', '0002_alter_termscore_expectation_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAggregatePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField()),
                ('avg_expectation_level', models.CharField(blank=True, max_length=100)),
                ('grade_scores', models.TextField(blank=True)),
                ('bloom_skill_scores', models.TextField(blank=True)),
                ('strand_analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_exam_performance', to='learner.classroom')),
            ],
        ),
    ]
