# Generated by Django 5.1.7 on 2025-06-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_classroomexamaggregateperformance'),
        ('learner', '0002_alter_termscore_expectation_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='classaggregateperformance',
            name='exam_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentAggregatePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_count', models.IntegerField(default=0)),
                ('avg_score', models.FloatField()),
                ('avg_expectation_level', models.CharField(blank=True, max_length=100)),
                ('bloom_skill_scores', models.TextField(blank=True)),
                ('grade_scores', models.TextField(blank=True)),
                ('strand_scores', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_performance', to='learner.student')),
            ],
        ),
    ]
