name: Deploy to digital ocean

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Connect to droplet via SSH and deploy
      - name: Deploy to droplet via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP` }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22 # Use the correct SSH port if it's not 22
          script: |
            echo "Pulling latest changes on droplet..."
            pushd /var/www/mtihani
            git pull origin main
            sudo systemctl restart supervisor
            echo "Deployment complete!"

 